package com.hlxd.glhdcs.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSReplacelogExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_S_REPLACELOG
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_S_REPLACELOG
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_S_REPLACELOG
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     *  构造查询条件,T_S_REPLACELOG
     */
    public TSReplacelogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,T_S_REPLACELOG
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,T_S_REPLACELOG
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,T_S_REPLACELOG
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,T_S_REPLACELOG
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,T_S_REPLACELOG
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,T_S_REPLACELOG
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,T_S_REPLACELOG
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,T_S_REPLACELOG
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,T_S_REPLACELOG
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,T_S_REPLACELOG
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 替代记录表
     * GeneratedCriteria
     * 数据库表：T_S_REPLACELOG
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReplacelogIdIsNull() {
            addCriterion("REPLACELOG_ID is null");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdIsNotNull() {
            addCriterion("REPLACELOG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdEqualTo(String value) {
            addCriterion("REPLACELOG_ID =", value, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdNotEqualTo(String value) {
            addCriterion("REPLACELOG_ID <>", value, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdGreaterThan(String value) {
            addCriterion("REPLACELOG_ID >", value, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdGreaterThanOrEqualTo(String value) {
            addCriterion("REPLACELOG_ID >=", value, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdLessThan(String value) {
            addCriterion("REPLACELOG_ID <", value, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdLessThanOrEqualTo(String value) {
            addCriterion("REPLACELOG_ID <=", value, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdLike(String value) {
            addCriterion("REPLACELOG_ID like", value, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdNotLike(String value) {
            addCriterion("REPLACELOG_ID not like", value, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdIn(List<String> values) {
            addCriterion("REPLACELOG_ID in", values, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdNotIn(List<String> values) {
            addCriterion("REPLACELOG_ID not in", values, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdBetween(String value1, String value2) {
            addCriterion("REPLACELOG_ID between", value1, value2, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andReplacelogIdNotBetween(String value1, String value2) {
            addCriterion("REPLACELOG_ID not between", value1, value2, "replacelogId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdIsNull() {
            addCriterion("SOLUTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andSolutionIdIsNotNull() {
            addCriterion("SOLUTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSolutionIdEqualTo(String value) {
            addCriterion("SOLUTION_ID =", value, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdNotEqualTo(String value) {
            addCriterion("SOLUTION_ID <>", value, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdGreaterThan(String value) {
            addCriterion("SOLUTION_ID >", value, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdGreaterThanOrEqualTo(String value) {
            addCriterion("SOLUTION_ID >=", value, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdLessThan(String value) {
            addCriterion("SOLUTION_ID <", value, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdLessThanOrEqualTo(String value) {
            addCriterion("SOLUTION_ID <=", value, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdLike(String value) {
            addCriterion("SOLUTION_ID like", value, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdNotLike(String value) {
            addCriterion("SOLUTION_ID not like", value, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdIn(List<String> values) {
            addCriterion("SOLUTION_ID in", values, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdNotIn(List<String> values) {
            addCriterion("SOLUTION_ID not in", values, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdBetween(String value1, String value2) {
            addCriterion("SOLUTION_ID between", value1, value2, "solutionId");
            return (Criteria) this;
        }

        public Criteria andSolutionIdNotBetween(String value1, String value2) {
            addCriterion("SOLUTION_ID not between", value1, value2, "solutionId");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeIsNull() {
            addCriterion("OBSOLETE_UNIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeIsNotNull() {
            addCriterion("OBSOLETE_UNIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_CODE =", value, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeNotEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_CODE <>", value, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeGreaterThan(String value) {
            addCriterion("OBSOLETE_UNIT_CODE >", value, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_CODE >=", value, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeLessThan(String value) {
            addCriterion("OBSOLETE_UNIT_CODE <", value, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_CODE <=", value, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeLike(String value) {
            addCriterion("OBSOLETE_UNIT_CODE like", value, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeNotLike(String value) {
            addCriterion("OBSOLETE_UNIT_CODE not like", value, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_CODE in", values, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeNotIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_CODE not in", values, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_CODE between", value1, value2, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitCodeNotBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_CODE not between", value1, value2, "obsoleteUnitCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameIsNull() {
            addCriterion("OBSOLETE_UNIT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameIsNotNull() {
            addCriterion("OBSOLETE_UNIT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_NAME =", value, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameNotEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_NAME <>", value, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameGreaterThan(String value) {
            addCriterion("OBSOLETE_UNIT_NAME >", value, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_NAME >=", value, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameLessThan(String value) {
            addCriterion("OBSOLETE_UNIT_NAME <", value, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameLessThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_NAME <=", value, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameLike(String value) {
            addCriterion("OBSOLETE_UNIT_NAME like", value, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameNotLike(String value) {
            addCriterion("OBSOLETE_UNIT_NAME not like", value, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_NAME in", values, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameNotIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_NAME not in", values, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_NAME between", value1, value2, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitNameNotBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_NAME not between", value1, value2, "obsoleteUnitName");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeIsNull() {
            addCriterion("OBSOLETE_UNIT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeIsNotNull() {
            addCriterion("OBSOLETE_UNIT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_TYPE =", value, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeNotEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_TYPE <>", value, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeGreaterThan(String value) {
            addCriterion("OBSOLETE_UNIT_TYPE >", value, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_TYPE >=", value, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeLessThan(String value) {
            addCriterion("OBSOLETE_UNIT_TYPE <", value, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeLessThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_TYPE <=", value, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeLike(String value) {
            addCriterion("OBSOLETE_UNIT_TYPE like", value, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeNotLike(String value) {
            addCriterion("OBSOLETE_UNIT_TYPE not like", value, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_TYPE in", values, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeNotIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_TYPE not in", values, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_TYPE between", value1, value2, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitTypeNotBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_TYPE not between", value1, value2, "obsoleteUnitType");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelIsNull() {
            addCriterion("OBSOLETE_UNIT_MODEL is null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelIsNotNull() {
            addCriterion("OBSOLETE_UNIT_MODEL is not null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_MODEL =", value, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelNotEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_MODEL <>", value, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelGreaterThan(String value) {
            addCriterion("OBSOLETE_UNIT_MODEL >", value, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelGreaterThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_MODEL >=", value, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelLessThan(String value) {
            addCriterion("OBSOLETE_UNIT_MODEL <", value, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelLessThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_MODEL <=", value, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelLike(String value) {
            addCriterion("OBSOLETE_UNIT_MODEL like", value, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelNotLike(String value) {
            addCriterion("OBSOLETE_UNIT_MODEL not like", value, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_MODEL in", values, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelNotIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_MODEL not in", values, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_MODEL between", value1, value2, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitModelNotBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_MODEL not between", value1, value2, "obsoleteUnitModel");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierIsNull() {
            addCriterion("OBSOLETE_UNIT_SUPPLIER is null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierIsNotNull() {
            addCriterion("OBSOLETE_UNIT_SUPPLIER is not null");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER =", value, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierNotEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER <>", value, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierGreaterThan(String value) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER >", value, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER >=", value, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierLessThan(String value) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER <", value, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierLessThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER <=", value, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierLike(String value) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER like", value, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierNotLike(String value) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER not like", value, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER in", values, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierNotIn(List<String> values) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER not in", values, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER between", value1, value2, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andObsoleteUnitSupplierNotBetween(String value1, String value2) {
            addCriterion("OBSOLETE_UNIT_SUPPLIER not between", value1, value2, "obsoleteUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeIsNull() {
            addCriterion("REPLACE_UNIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeIsNotNull() {
            addCriterion("REPLACE_UNIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeEqualTo(String value) {
            addCriterion("REPLACE_UNIT_CODE =", value, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeNotEqualTo(String value) {
            addCriterion("REPLACE_UNIT_CODE <>", value, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeGreaterThan(String value) {
            addCriterion("REPLACE_UNIT_CODE >", value, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_CODE >=", value, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeLessThan(String value) {
            addCriterion("REPLACE_UNIT_CODE <", value, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_CODE <=", value, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeLike(String value) {
            addCriterion("REPLACE_UNIT_CODE like", value, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeNotLike(String value) {
            addCriterion("REPLACE_UNIT_CODE not like", value, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeIn(List<String> values) {
            addCriterion("REPLACE_UNIT_CODE in", values, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeNotIn(List<String> values) {
            addCriterion("REPLACE_UNIT_CODE not in", values, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_CODE between", value1, value2, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitCodeNotBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_CODE not between", value1, value2, "replaceUnitCode");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameIsNull() {
            addCriterion("REPLACE_UNIT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameIsNotNull() {
            addCriterion("REPLACE_UNIT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameEqualTo(String value) {
            addCriterion("REPLACE_UNIT_NAME =", value, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameNotEqualTo(String value) {
            addCriterion("REPLACE_UNIT_NAME <>", value, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameGreaterThan(String value) {
            addCriterion("REPLACE_UNIT_NAME >", value, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_NAME >=", value, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameLessThan(String value) {
            addCriterion("REPLACE_UNIT_NAME <", value, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameLessThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_NAME <=", value, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameLike(String value) {
            addCriterion("REPLACE_UNIT_NAME like", value, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameNotLike(String value) {
            addCriterion("REPLACE_UNIT_NAME not like", value, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameIn(List<String> values) {
            addCriterion("REPLACE_UNIT_NAME in", values, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameNotIn(List<String> values) {
            addCriterion("REPLACE_UNIT_NAME not in", values, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_NAME between", value1, value2, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitNameNotBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_NAME not between", value1, value2, "replaceUnitName");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeIsNull() {
            addCriterion("REPLACE_UNIT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeIsNotNull() {
            addCriterion("REPLACE_UNIT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeEqualTo(String value) {
            addCriterion("REPLACE_UNIT_TYPE =", value, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeNotEqualTo(String value) {
            addCriterion("REPLACE_UNIT_TYPE <>", value, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeGreaterThan(String value) {
            addCriterion("REPLACE_UNIT_TYPE >", value, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeGreaterThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_TYPE >=", value, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeLessThan(String value) {
            addCriterion("REPLACE_UNIT_TYPE <", value, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeLessThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_TYPE <=", value, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeLike(String value) {
            addCriterion("REPLACE_UNIT_TYPE like", value, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeNotLike(String value) {
            addCriterion("REPLACE_UNIT_TYPE not like", value, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeIn(List<String> values) {
            addCriterion("REPLACE_UNIT_TYPE in", values, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeNotIn(List<String> values) {
            addCriterion("REPLACE_UNIT_TYPE not in", values, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_TYPE between", value1, value2, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitTypeNotBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_TYPE not between", value1, value2, "replaceUnitType");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelIsNull() {
            addCriterion("REPLACE_UNIT_MODEL is null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelIsNotNull() {
            addCriterion("REPLACE_UNIT_MODEL is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelEqualTo(String value) {
            addCriterion("REPLACE_UNIT_MODEL =", value, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelNotEqualTo(String value) {
            addCriterion("REPLACE_UNIT_MODEL <>", value, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelGreaterThan(String value) {
            addCriterion("REPLACE_UNIT_MODEL >", value, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelGreaterThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_MODEL >=", value, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelLessThan(String value) {
            addCriterion("REPLACE_UNIT_MODEL <", value, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelLessThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_MODEL <=", value, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelLike(String value) {
            addCriterion("REPLACE_UNIT_MODEL like", value, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelNotLike(String value) {
            addCriterion("REPLACE_UNIT_MODEL not like", value, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelIn(List<String> values) {
            addCriterion("REPLACE_UNIT_MODEL in", values, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelNotIn(List<String> values) {
            addCriterion("REPLACE_UNIT_MODEL not in", values, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_MODEL between", value1, value2, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitModelNotBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_MODEL not between", value1, value2, "replaceUnitModel");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierIsNull() {
            addCriterion("REPLACE_UNIT_SUPPLIER is null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierIsNotNull() {
            addCriterion("REPLACE_UNIT_SUPPLIER is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierEqualTo(String value) {
            addCriterion("REPLACE_UNIT_SUPPLIER =", value, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierNotEqualTo(String value) {
            addCriterion("REPLACE_UNIT_SUPPLIER <>", value, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierGreaterThan(String value) {
            addCriterion("REPLACE_UNIT_SUPPLIER >", value, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_SUPPLIER >=", value, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierLessThan(String value) {
            addCriterion("REPLACE_UNIT_SUPPLIER <", value, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierLessThanOrEqualTo(String value) {
            addCriterion("REPLACE_UNIT_SUPPLIER <=", value, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierLike(String value) {
            addCriterion("REPLACE_UNIT_SUPPLIER like", value, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierNotLike(String value) {
            addCriterion("REPLACE_UNIT_SUPPLIER not like", value, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierIn(List<String> values) {
            addCriterion("REPLACE_UNIT_SUPPLIER in", values, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierNotIn(List<String> values) {
            addCriterion("REPLACE_UNIT_SUPPLIER not in", values, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_SUPPLIER between", value1, value2, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceUnitSupplierNotBetween(String value1, String value2) {
            addCriterion("REPLACE_UNIT_SUPPLIER not between", value1, value2, "replaceUnitSupplier");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeIsNull() {
            addCriterion("REPLACE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeIsNotNull() {
            addCriterion("REPLACE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeEqualTo(Date value) {
            addCriterion("REPLACE_TIME =", value, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeNotEqualTo(Date value) {
            addCriterion("REPLACE_TIME <>", value, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeGreaterThan(Date value) {
            addCriterion("REPLACE_TIME >", value, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REPLACE_TIME >=", value, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeLessThan(Date value) {
            addCriterion("REPLACE_TIME <", value, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeLessThanOrEqualTo(Date value) {
            addCriterion("REPLACE_TIME <=", value, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeIn(List<Date> values) {
            addCriterion("REPLACE_TIME in", values, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeNotIn(List<Date> values) {
            addCriterion("REPLACE_TIME not in", values, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeBetween(Date value1, Date value2) {
            addCriterion("REPLACE_TIME between", value1, value2, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andReplaceTimeNotBetween(Date value1, Date value2) {
            addCriterion("REPLACE_TIME not between", value1, value2, "replaceTime");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeIsNull() {
            addCriterion("OBSOLETE_EQUIPMENT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeIsNotNull() {
            addCriterion("OBSOLETE_EQUIPMENT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeEqualTo(String value) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE =", value, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeNotEqualTo(String value) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE <>", value, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeGreaterThan(String value) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE >", value, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE >=", value, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeLessThan(String value) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE <", value, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeLessThanOrEqualTo(String value) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE <=", value, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeLike(String value) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE like", value, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeNotLike(String value) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE not like", value, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeIn(List<String> values) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE in", values, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeNotIn(List<String> values) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE not in", values, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeBetween(String value1, String value2) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE between", value1, value2, "obsoleteEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andObsoleteEquipmentCodeNotBetween(String value1, String value2) {
            addCriterion("OBSOLETE_EQUIPMENT_CODE not between", value1, value2, "obsoleteEquipmentCode");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：T_S_REPLACELOG
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 替代记录表
     * Criterion
     * 数据库表：T_S_REPLACELOG
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}