package com.hlxd.glhdcs.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TSSurrenalStopTendExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_S_SURRENAL_STOP_TEND
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_S_SURRENAL_STOP_TEND
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_S_SURRENAL_STOP_TEND
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     *  构造查询条件,T_S_SURRENAL_STOP_TEND
     */
    public TSSurrenalStopTendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,T_S_SURRENAL_STOP_TEND
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,T_S_SURRENAL_STOP_TEND
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,T_S_SURRENAL_STOP_TEND
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,T_S_SURRENAL_STOP_TEND
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,T_S_SURRENAL_STOP_TEND
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,T_S_SURRENAL_STOP_TEND
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,T_S_SURRENAL_STOP_TEND
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,T_S_SURRENAL_STOP_TEND
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,T_S_SURRENAL_STOP_TEND
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,T_S_SURRENAL_STOP_TEND
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 停产物资维护表
     * GeneratedCriteria
     * 数据库表：T_S_SURRENAL_STOP_TEND
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andStopSupplieIdIsNull() {
            addCriterion("STOP_SUPPLIE_ID is null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdIsNotNull() {
            addCriterion("STOP_SUPPLIE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_ID =", value, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdNotEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_ID <>", value, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdGreaterThan(String value) {
            addCriterion("STOP_SUPPLIE_ID >", value, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdGreaterThanOrEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_ID >=", value, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdLessThan(String value) {
            addCriterion("STOP_SUPPLIE_ID <", value, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdLessThanOrEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_ID <=", value, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdLike(String value) {
            addCriterion("STOP_SUPPLIE_ID like", value, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdNotLike(String value) {
            addCriterion("STOP_SUPPLIE_ID not like", value, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdIn(List<String> values) {
            addCriterion("STOP_SUPPLIE_ID in", values, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdNotIn(List<String> values) {
            addCriterion("STOP_SUPPLIE_ID not in", values, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdBetween(String value1, String value2) {
            addCriterion("STOP_SUPPLIE_ID between", value1, value2, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieIdNotBetween(String value1, String value2) {
            addCriterion("STOP_SUPPLIE_ID not between", value1, value2, "stopSupplieId");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameIsNull() {
            addCriterion("STOP_SUPPLIE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameIsNotNull() {
            addCriterion("STOP_SUPPLIE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_NAME =", value, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameNotEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_NAME <>", value, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameGreaterThan(String value) {
            addCriterion("STOP_SUPPLIE_NAME >", value, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameGreaterThanOrEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_NAME >=", value, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameLessThan(String value) {
            addCriterion("STOP_SUPPLIE_NAME <", value, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameLessThanOrEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_NAME <=", value, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameLike(String value) {
            addCriterion("STOP_SUPPLIE_NAME like", value, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameNotLike(String value) {
            addCriterion("STOP_SUPPLIE_NAME not like", value, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameIn(List<String> values) {
            addCriterion("STOP_SUPPLIE_NAME in", values, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameNotIn(List<String> values) {
            addCriterion("STOP_SUPPLIE_NAME not in", values, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameBetween(String value1, String value2) {
            addCriterion("STOP_SUPPLIE_NAME between", value1, value2, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieNameNotBetween(String value1, String value2) {
            addCriterion("STOP_SUPPLIE_NAME not between", value1, value2, "stopSupplieName");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeIsNull() {
            addCriterion("MATERIAL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeIsNotNull() {
            addCriterion("MATERIAL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeEqualTo(String value) {
            addCriterion("MATERIAL_CODE =", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeNotEqualTo(String value) {
            addCriterion("MATERIAL_CODE <>", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeGreaterThan(String value) {
            addCriterion("MATERIAL_CODE >", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL_CODE >=", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeLessThan(String value) {
            addCriterion("MATERIAL_CODE <", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL_CODE <=", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeLike(String value) {
            addCriterion("MATERIAL_CODE like", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeNotLike(String value) {
            addCriterion("MATERIAL_CODE not like", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeIn(List<String> values) {
            addCriterion("MATERIAL_CODE in", values, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeNotIn(List<String> values) {
            addCriterion("MATERIAL_CODE not in", values, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeBetween(String value1, String value2) {
            addCriterion("MATERIAL_CODE between", value1, value2, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeNotBetween(String value1, String value2) {
            addCriterion("MATERIAL_CODE not between", value1, value2, "materialCode");
            return (Criteria) this;
        }

        public Criteria andEmModelNameIsNull() {
            addCriterion("EM_MODEL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEmModelNameIsNotNull() {
            addCriterion("EM_MODEL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEmModelNameEqualTo(String value) {
            addCriterion("EM_MODEL_NAME =", value, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameNotEqualTo(String value) {
            addCriterion("EM_MODEL_NAME <>", value, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameGreaterThan(String value) {
            addCriterion("EM_MODEL_NAME >", value, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameGreaterThanOrEqualTo(String value) {
            addCriterion("EM_MODEL_NAME >=", value, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameLessThan(String value) {
            addCriterion("EM_MODEL_NAME <", value, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameLessThanOrEqualTo(String value) {
            addCriterion("EM_MODEL_NAME <=", value, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameLike(String value) {
            addCriterion("EM_MODEL_NAME like", value, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameNotLike(String value) {
            addCriterion("EM_MODEL_NAME not like", value, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameIn(List<String> values) {
            addCriterion("EM_MODEL_NAME in", values, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameNotIn(List<String> values) {
            addCriterion("EM_MODEL_NAME not in", values, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameBetween(String value1, String value2) {
            addCriterion("EM_MODEL_NAME between", value1, value2, "emModelName");
            return (Criteria) this;
        }

        public Criteria andEmModelNameNotBetween(String value1, String value2) {
            addCriterion("EM_MODEL_NAME not between", value1, value2, "emModelName");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeIsNull() {
            addCriterion("STOP_SUPPLIE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeIsNotNull() {
            addCriterion("STOP_SUPPLIE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_TYPE =", value, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeNotEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_TYPE <>", value, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeGreaterThan(String value) {
            addCriterion("STOP_SUPPLIE_TYPE >", value, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeGreaterThanOrEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_TYPE >=", value, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeLessThan(String value) {
            addCriterion("STOP_SUPPLIE_TYPE <", value, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeLessThanOrEqualTo(String value) {
            addCriterion("STOP_SUPPLIE_TYPE <=", value, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeLike(String value) {
            addCriterion("STOP_SUPPLIE_TYPE like", value, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeNotLike(String value) {
            addCriterion("STOP_SUPPLIE_TYPE not like", value, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeIn(List<String> values) {
            addCriterion("STOP_SUPPLIE_TYPE in", values, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeNotIn(List<String> values) {
            addCriterion("STOP_SUPPLIE_TYPE not in", values, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeBetween(String value1, String value2) {
            addCriterion("STOP_SUPPLIE_TYPE between", value1, value2, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieTypeNotBetween(String value1, String value2) {
            addCriterion("STOP_SUPPLIE_TYPE not between", value1, value2, "stopSupplieType");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierIsNull() {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" is null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierIsNotNull() {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" is not null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierEqualTo(String value) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" =", value, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierNotEqualTo(String value) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" <>", value, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierGreaterThan(String value) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" >", value, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" >=", value, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierLessThan(String value) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" <", value, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierLessThanOrEqualTo(String value) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" <=", value, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierLike(String value) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" like", value, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierNotLike(String value) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" not like", value, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierIn(List<String> values) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" in", values, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierNotIn(List<String> values) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" not in", values, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierBetween(String value1, String value2) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" between", value1, value2, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopSupplieSupplierNotBetween(String value1, String value2) {
            addCriterion("\"STOP_SUPPLIE _ SUPPLIER\" not between", value1, value2, "stopSupplieSupplier");
            return (Criteria) this;
        }

        public Criteria andStopCauseIsNull() {
            addCriterion("STOP_CAUSE is null");
            return (Criteria) this;
        }

        public Criteria andStopCauseIsNotNull() {
            addCriterion("STOP_CAUSE is not null");
            return (Criteria) this;
        }

        public Criteria andStopCauseEqualTo(String value) {
            addCriterion("STOP_CAUSE =", value, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseNotEqualTo(String value) {
            addCriterion("STOP_CAUSE <>", value, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseGreaterThan(String value) {
            addCriterion("STOP_CAUSE >", value, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseGreaterThanOrEqualTo(String value) {
            addCriterion("STOP_CAUSE >=", value, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseLessThan(String value) {
            addCriterion("STOP_CAUSE <", value, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseLessThanOrEqualTo(String value) {
            addCriterion("STOP_CAUSE <=", value, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseLike(String value) {
            addCriterion("STOP_CAUSE like", value, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseNotLike(String value) {
            addCriterion("STOP_CAUSE not like", value, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseIn(List<String> values) {
            addCriterion("STOP_CAUSE in", values, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseNotIn(List<String> values) {
            addCriterion("STOP_CAUSE not in", values, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseBetween(String value1, String value2) {
            addCriterion("STOP_CAUSE between", value1, value2, "stopCause");
            return (Criteria) this;
        }

        public Criteria andStopCauseNotBetween(String value1, String value2) {
            addCriterion("STOP_CAUSE not between", value1, value2, "stopCause");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNull() {
            addCriterion("IS_ENABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNotNull() {
            addCriterion("IS_ENABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnableEqualTo(Boolean value) {
            addCriterion("IS_ENABLE =", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotEqualTo(Boolean value) {
            addCriterion("IS_ENABLE <>", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThan(Boolean value) {
            addCriterion("IS_ENABLE >", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_ENABLE >=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThan(Boolean value) {
            addCriterion("IS_ENABLE <", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_ENABLE <=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableIn(List<Boolean> values) {
            addCriterion("IS_ENABLE in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotIn(List<Boolean> values) {
            addCriterion("IS_ENABLE not in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_ENABLE between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_ENABLE not between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeIsNull() {
            addCriterion("\"STOP_SUPPLIE _ DOWNTIME\" is null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeIsNotNull() {
            addCriterion("\"STOP_SUPPLIE _ DOWNTIME\" is not null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeEqualTo(Date value) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" =", value, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" <>", value, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeGreaterThan(Date value) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" >", value, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" >=", value, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeLessThan(Date value) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" <", value, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" <=", value, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeIn(List<Date> values) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" in", values, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" not in", values, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" between", value1, value2, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieDowntimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"STOP_SUPPLIE _ DOWNTIME\" not between", value1, value2, "stopSupplieDowntime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeIsNull() {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" is null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeIsNotNull() {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" is not null");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeEqualTo(Date value) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" =", value, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeNotEqualTo(Date value) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" <>", value, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeGreaterThan(Date value) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" >", value, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" >=", value, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeLessThan(Date value) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" <", value, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeLessThanOrEqualTo(Date value) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" <=", value, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeIn(List<Date> values) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" in", values, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeNotIn(List<Date> values) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" not in", values, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeBetween(Date value1, Date value2) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" between", value1, value2, "stopSupplieWritetime");
            return (Criteria) this;
        }

        public Criteria andStopSupplieWritetimeNotBetween(Date value1, Date value2) {
            addCriterion("\"STOP_SUPPLIE _ WRITETIME\" not between", value1, value2, "stopSupplieWritetime");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：T_S_SURRENAL_STOP_TEND
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 停产物资维护表
     * Criterion
     * 数据库表：T_S_SURRENAL_STOP_TEND
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}